# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 1

[[main]]
  name = "Blog"
  url = "#posts"
  weight = 3

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 2

[[main]]
  name = "Teaching"
  url = "#teaching"
  weight = 4

[[main]]
  name = "Consulting"
  url = "#consulting"
  weight = 5

[[main]]
  name = "OPRA"
  url = "#opra"
  weight = 6

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 8

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 7
